#!/bin/bash
#SBATCH --job-name wfh
#SBATCH -p production
#SBATCH --mail-user=nganju@usgs.gov
#SBATCH --mail-type=ALL
#SBATCH -o wfh.out-%j
#SBATCH -e wfh.err-%j
#SBATCH -n 1

cd /scylla-a/home/nganju/wfh


# mpirun will pull the number of cores from SGE
mpirun ./coawstM <./external/ocean_wfh_VEG.in >wfh_oxygen_Pilar_spect.out

